name: Build wheels

on:
  push:
    branches:
      - master
    tags:
      - v* # Push events to v* tags
  # pull_request:
  #   branches:
  #     - master
  # Manual run
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  # Build wheels for macOS, Linux, and Windows
  build_wheels:
    name: Wheel for ${{ matrix.os }}-cp${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    strategy:
      # Build the other wheels even if one fails
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: [310]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4

      # - name: Setup cmake
      #   uses: jwlawson/actions-setup-cmake@v1.9
      #   with:
      #     cmake-version: '3.16.x'

      - name: Install boost on Windows
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: 2019
          toolset: msvc
        if: runner.os == 'Windows'

      - name: Install boost on Linux
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: 20.04
          toolset: gcc
        if: runner.os == 'Linux'

      - name: Install boost on macOS
        run: |
          brew upgrade
          brew install boost
        shell: bash
        if: runner.os == 'macOS'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BUILD: cp${{ matrix.python }}-*
          CIBW_ARCHS_MACOS: x86_64 arm64
          # CIBW_ARCHS_MACOS: x86_64
          CIBW_ARCHS_LINUX: auto aarch64

      - name: Show files
        run: ls -lh wheelhouse
        shell: bash

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
